default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000

development:
  <<: *default
  database: betterspace_dev

test:
  <<: *default
  database: betterspace_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
