development:
  adapter:  postgresql
  encoding: unicode
  database:  betterspace_dev
  pool:     5
  host: localhost
  username: deploy
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: betterspace_test
  host: localhost
  pool: 5
  username: deploy
  password: password1

production:
  adapter:  postgresql
  encoding: unicode
  database: betterspace_dev
  host: localhost
  pool:     5
  username: deploy
  password: password1
