production:
  adapter: postgresql
  encoding: unicode
  database: betterspace
  pool: 5
  username: Persistence
  password: password1

development:
  adapter: postgresql
  encoding: unicode
  database: betterspace_development
  pool: 5
  username: Persistence
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: betterspace_test
  pool: 5
  username: Persistence
  password: password1
